/*TIPO PRODUCTO*/
INSERT INTO TBL_TIPOPRODUCTO VALUES (0, 'Alimento', 'Comida');
INSERT INTO TBL_TIPOPRODUCTO VALUES (1, 'Mantenimiento', 'Servicio');
INSERT INTO TBL_TIPOPRODUCTO VALUES (2, 'Venta', 'Ganancia');
/*
ALTER TABLE TBL_TIPOPRODUCTO ADD ESTADO TINYINT (1) DEFAULT 1;

INSERT INTO TBL_TIPOPRODUCTO VALUES (0, 'Alimento', 'Comida', 1);
INSERT INTO TBL_TIPOPRODUCTO VALUES (1, 'Mantenimiento', 'Servicio', 1);
INSERT INTO TBL_TIPOPRODUCTO VALUES (2, 'Venta', 'Ganancia', 1);
*/

/*PRODUCTO*/
INSERT INTO TBL_PRODUCTO VALUES (0, 0, 'Pasta', 'Fideos', 1);
INSERT INTO TBL_PRODUCTO VALUES (1, 0, 'Leche', 'Lacteo', 1);

/*SUCURSAL*/
INSERT INTO TBL_SUCURSAL VALUES (0, 'Hotel', 'Direccion', 1);

/*BODEGA*/
INSERT INTO TBL_BODEGA VALUES (0, 0, 'Principal', 'Principal del hotel', 'Direccion hotel', 0, 999, 'Status 0', 1);
INSERT INTO TBL_BODEGA VALUES (1, 0, 'Alimentos', 'Almacen de alimentos', 'Direccion hotel', 0, 999, 'Status 1', 1);

/*STOCK*/
INSERT INTO TBL_STOCK VALUES (0, 999999999, 10, 1);
INSERT INTO TBL_STOCK VALUES (1, 999999990, 0, 1);

/*EXISTENCIA*/
INSERT INTO TBL_EXISTENCIA VALUES (0, 0, '50 unidad', 1);
INSERT INTO TBL_EXISTENCIA VALUES (1, 1, '60 unidad', 1);

/*MARCA*/
INSERT INTO TBL_MARCA VALUES (0, 'Marca 1', 'Guatemala', 1);
INSERT INTO TBL_MARCA VALUES (1, 'Marca 2', 'Guatemala', 1);

/*PRODUCTO DETALLE*/
INSERT INTO TBL_DETALLE_PRODUCTO VALUES (0, 0, 'Artesanal', "10 kg", 'Integral', 1);
INSERT INTO TBL_DETALLE_PRODUCTO VALUES (1, 1, 'Ligth', "1 gl", 'Sin conservantes', 1);

/*UBICACION*/
INSERT INTO TBL_UBICACION VALUES (0, 'Hotel', '0-99 calle, Zona 1', 999999999, 1);

/*PRODUCTO MARCA*/

INSERT INTO TBL_PRODUCTO_MARCA VALUES (0, 0);
INSERT INTO TBL_PRODUCTO_MARCA VALUES (1, 1);
/*
ALTER TABLE TBL_PRODUCTO_MARCA ADD ESTADO TINYINT (1) DEFAULT 1;

INSERT INTO TBL_PRODUCTO_MARCA VALUES (0, 0, 1);
INSERT INTO TBL_PRODUCTO_MARCA VALUES (1, 1, 1);
*/

/*MOVIMIENTO INVENTARIO*/
INSERT INTO TBL_MOVIeMIENTO_INVENTARIO VALUES (0, 'MOV 1', 'Salida', 1);
INSERT INTO TBL_MOVIeMIENTO_INVENTARIO VALUES (1, 'MOV 2', 'Entrada', 1);

/*HISTORIAL INVENTARIO*/
INSERT INTO TBL_HISTORIA_INVENTARIO VALUES (0, 0, 1, 0, '2019-11-01 10:00:00', '50 unidades', 1);

commit;

